In [1]:
import pandas as pd

## events -> dataset

In [7]:
df = pd.read_csv("../data/raw/events.csv")

In [8]:
df.head()

       timestamp  visitorid event  itemid  transactionid
0  1433221332117     257597  view  355908            NaN
1  1433224214164     992329  view  248676            NaN
2  1433221999827     111016  view  318965            NaN
3  1433221955914     483717  view  253185            NaN
4  1433221337106     951259  view  367447            NaN

In [10]:
df.shape

(2756101, 5)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2756101 entries, 0 to 2756100
Data columns (total 5 columns):
 #   Column         Dtype
---  ------         -----
 0   timestamp      int64
 1   visitorid      int64
 2   event          str
 3   itemid         int64
 4   transactionid  float64
dtypes: float64(1), int64(3), str(1)
memory usage: 105.1 MB

In [18]:
df["visitorid"].nunique()

1407580

In [19]:
df["itemid"].nunique()

235061

In [20]:
df["event"].value_counts()

event
view           2664312
addtocart        69332
transaction      22457
Name: count, dtype: int64

In [21]:
df["visitorid"].nunique() * df["itemid"].nunique()

330867162380

## item_properties -> dataset

In [22]:
items = pd.read_csv("../data/raw/item_properties_part1.csv")

In [23]:
items.head()

       timestamp  itemid    property                            value
0  1435460400000  460429  categoryid                             1338
1  1441508400000  206783         888          1116713 960601 n277.200
2  1439089200000  395014         400  n552.000 639502 n720.000 424566
3  1431226800000   59481         790                       n15360.000
4  1431831600000  156781         917                           828513

In [24]:
items.shape

(10999999, 4)

In [25]:
items["property"].nunique()

1097

In [29]:
items["property"].value_counts().head(15)

property
888           1629817
790            970800
available      817387
categoryid     426305
6              343207
283            323681
776            311654
678            261829
364            256340
202            242984
839            226921
159            226502
917            226437
764            226242
112            226102
Name: count, dtype: int64

In [33]:
items["itemid"].nunique()

417053

In [32]:
items.shape

(10999999, 4)

## category_tree -> dataset

In [30]:
categories = pd.read_csv("../data/raw/category_tree.csv")

In [31]:
categories.head()

   categoryid  parentid
0        1016     213.0
1         809     169.0
2         570       9.0
3        1691     885.0
4         536    1691.0

## items2 -> dataset

In [34]:
items2 = pd.read_csv("../data/raw/item_properties_part2.csv")

In [35]:
items.head()

       timestamp  itemid    property                            value
0  1435460400000  460429  categoryid                             1338
1  1441508400000  206783         888          1116713 960601 n277.200
2  1439089200000  395014         400  n552.000 639502 n720.000 424566
3  1431226800000   59481         790                       n15360.000
4  1431831600000  156781         917                           828513

In [36]:
items2.shape

(9275903, 4)

In [37]:
df['visitorid'].value_counts().head(15)

visitorid
1150086    7757
530559     4328
152963     3024
895999     2474
163561     2410
371606     2345
286616     2252
684514     2246
892013     2024
861299     1991
836635     1934
76757      1883
638482     1829
1297062    1822
316850     1752
Name: count, dtype: int64